const fs = require('fs');
const path = require('path');

const dir = path.join(process.cwd(), 'public', 'images', 'kavya-portfolio');
const files = fs.readdirSync(dir)
  .filter(f => /\.(jpg|jpeg|png|webp)$/i.test(f))
  .sort();

const dataDir = path.join(process.cwd(), 'data');
if (!fs.existsSync(dataDir)) fs.mkdirSync(dataDir, { recursive: true });

const content = `// Auto-generated by scripts/generateImageList.js
export const kavyaPortfolioImages = [
${files.map(f => `  "/images/kavya-portfolio/${f}"`).join(',\n')}
];
`;

fs.writeFileSync(
  path.join(dataDir, 'kavyaPortfolioImages.js'),
  content
);

console.log(`Generated list of ${files.length} images.`);
